### ISSUE TITLE
Getting all images for given object

### ISSUE THREAD

**Issue by ryanjdillon** [Kemaweyan/django-content-gallery#1]
First, I really like your app and thanks!

I'd like to generate an images gallery from an object passed in a detail view, and I'm having a hard time figuring out how to get a list of all images related to that object in my detail template. This is a personal problem, but hopefully it might help others too.

I'd rather just pass it in the context, rather than making a widget, or template tag, but I'm confused about how the `pk` of the object is stored with the images to do a query.

Essentially what I would like to do:
```
  {% for image in job.images %}
    <img src="{{ image.thumbnail_url }}>"
  {% endfor %}
```

Thanks!

**Comment by Kemaweyan** [comment]
If `job` is an object of your model that django-content-gallery is attached to, it should use the `ContentGalleryMixin` that provides the `content_gallery` field for the model. So to get all related to the object images the template would look like this:

```
{% for image in job.content_gallery %}
  <img src="{{ image.thumbnail_url }}>"
{% endfor %}
```

**Comment by ryanjdillon** [comment]
Great. That did this trick. Thanks for the quick response!
